// login
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN_FEEDBACK = 'RECEIVE_LOGIN_FEEDBACK'
export const HANDLE_LOGIN_ERROR = 'HANDLE_LOGIN_ERROR'

// logout
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const RECEIVE_LOGOUT_FEEDBACK = 'RECEIVE_LOGOUT_FEEDBACK'
export const HANDLE_LOGOUT_ERROR = 'HANDLE_LOGOUT_ERROR'

// products
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const HANDLE_FETCH_PRODUCTS_ERROR = 'HANDLE_FETCH_PRODUCTS_ERROR'

// product
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
export const HANDLE_FETCH_PRODUCT_ERROR = 'HANDLE_FETCH_PRODUCT_ERROR'

// edit product
export const REQUEST_EDIT_PRODUCT = 'REQUEST_EDIT_PRODUCT'
export const RECEIVE_EDIT_PRODUCT_FEEDBACK = 'RECEIVE_EDIT_PRODUCT_FEEDBACK'

// add product
export const REQUEST_ADD_PRODUCT = 'REQUEST_ADD_PRODUCT'
export const RECEIVE_ADD_PRODUCT_FEEDBACK = 'RECEIVE_ADD_PRODUCT_FEEDBACK'
export const HANDLE_ADD_PRODUCT_ERROR = 'HANDLE_ADD_PRODUCT_ERROR'

// delete product
export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT'
export const RECEIVE_DELETE_PRODUCT_FEEDBACK = 'RECEIVE_DELETE_PRODUCT_FEEDBACK'
export const HANDLE_DELETE_PRODUCT_ERROR = 'HANDLE_DELETE_PRODUCT_ERROR'