export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN_FEEDBACK = 'RECEIVE_LOGIN_FEEDBACK'

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const REQUEST_EDIT_PRODUCT = 'REQUEST_EDIT_PRODUCT'
export const RECEIVE_EDIT_PRODUCT_FEEDBACK = 'RECEIVE_EDIT_PRODUCT_FEEDBACK'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REQUEST_ADD_PRODUCT = 'REQUEST_ADD_PRODUCT'
export const RECEIVE_ADD_PRODUCT_FEEDBACK = 'RECEIVE_ADD_PRODUCT_FEEDBACK'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT'
export const RECEIVE_DELETE_PRODUCT_FEEDBACK = 'RECEIVE_DELETE_PRODUCT_FEEDBACK'